### ISSUE TITLE
The touchpad buttons prevent the cursor from being moved

### ISSUE THREAD

**Issue by fcole90** [hanipouspilot/ubuntu-fixes#2]
If you put a finger on the left button (left hand, not pushing the button) and try to move on the touchpad with another (right and) the cursor doesn't move. This is a bit annoying especially with operations like drag and drop or wide selections.

When the finger is on the button it should be ignored and move the cursor according to the movement of the other finger.

**Comment by hanipouspilot** [comment]
1. I do not quite get why you may need this. Why keep a finger on a button and move a cursor? Drag and drop or selection can be done without using buttons. Just double tap and drag. I guess the buttons are made only for the case, when the driver is not yet installed on Windows. I do not have Windows. If you can check how the driver works there, it would be of help.
2. It is possible to get system ignore button area. Here is one of the ways to do it.
http://askubuntu.com/questions/221664/how-to-tune-touchpad-for-smaller-area

**Comment by fcole90** [comment]
As you can read from the question, it's quite difficult to have your finger up in the air instead of it laying on the button (not pressing). Anyway thank you for the link, for the moment is does not work well (the area gets resized but the cursor stops moving too. If you tell me how to help you on the functioning of the Windows driver I'll be happy to help you ;)

**Comment by hanipouspilot** [comment]
I never use buttons, when the driver is installed. In Windows it works a different way?

**Comment by fcole90** [comment]
Yes, in Windows too you can use both buttons or tapping. But if you lay a finger over a button without pressing, it is not considered. So I can leave my left hand index finger laying on the left button to be ready to press it and move the cursor with the right index in the while.

**Comment by fcole90** [comment]
Anyway, thank you for this great work, without it using the touchpad was a pain :)

**Comment by hanipouspilot** [comment]
This is not my work. Mathias Gottshlag wrote this driver, I just help to use it in Ubuntu.
I stopped supporting these kernel builds and made a dkms driver. Link is in description.

It is not hard to make the driver work same way as in Windows, but different models have different button areas. And we do not know how to get this info from the touchpad or link model with these parameters. Focaltesh or Asus people refuse to help.

**Comment by hanipouspilot** [comment]
But I will look how touchpad responds on touch in the button area. Maybe it is possible to identify it.

**Comment by hanipouspilot** [comment]
Does two finger scroll work with Windows in the button area?

**Comment by hanipouspilot** [comment]
Or is the button area totally ignored?

**Comment by hanipouspilot** [comment]
After some investigation I found with help of other people that it is not the problem of this driver. It is a general bug of xorg-synaptics used in Ubuntu.

**Comment by fcole90** [comment]
Oh,  ok than. Thanks for the help anyway :)

**Comment by hanipouspilot** [comment]
If you use Ubuntu or some distro, which handles touchpad by xorg-synaptics, you can make a bugreport.
General problem is that when one finger is on touchpad, movement of a second is ignored, unless both fingers move. But I am afraid that Canonical won't be much interested in fixing that, since they are replacing xorg with Mir.

**Comment by fcole90** [comment]
Yes, that's possible, but I'll try anyway. Nevertheless xorg will stay legacy for a while before the complete switch :)

**Comment by hanipouspilot** [comment]
Just upgrade xorg-synaptics. If you have Ubuntu 14.04 by
change to xserver-xorg-lts-utopic. This issue has been fixed.

**Comment by fcole90** [comment]
Thank you, that's awesome :)
